import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./provider";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const InterFont = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={InterFont.className}
    >
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
